# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tarefas_pb2 as tarefas__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tarefas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GerenciadorDeTarefasStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarTarefa = channel.unary_unary(
                '/tarefas.GerenciadorDeTarefas/CriarTarefa',
                request_serializer=tarefas__pb2.TarefaRequest.SerializeToString,
                response_deserializer=tarefas__pb2.TarefaResponse.FromString,
                _registered_method=True)
        self.ListarTarefas = channel.unary_unary(
                '/tarefas.GerenciadorDeTarefas/ListarTarefas',
                request_serializer=tarefas__pb2.ListaRequest.SerializeToString,
                response_deserializer=tarefas__pb2.ListaResponse.FromString,
                _registered_method=True)
        self.AtualizarTarefa = channel.unary_unary(
                '/tarefas.GerenciadorDeTarefas/AtualizarTarefa',
                request_serializer=tarefas__pb2.TarefaAtualizacaoRequest.SerializeToString,
                response_deserializer=tarefas__pb2.TarefaResponse.FromString,
                _registered_method=True)
        self.DeletarTarefa = channel.unary_unary(
                '/tarefas.GerenciadorDeTarefas/DeletarTarefa',
                request_serializer=tarefas__pb2.DeletarRequest.SerializeToString,
                response_deserializer=tarefas__pb2.DeletarResponse.FromString,
                _registered_method=True)


class GerenciadorDeTarefasServicer:
    """Missing associated documentation comment in .proto file."""

    def CriarTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarTarefas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletarTarefa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GerenciadorDeTarefasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarTarefa,
                    request_deserializer=tarefas__pb2.TarefaRequest.FromString,
                    response_serializer=tarefas__pb2.TarefaResponse.SerializeToString,
            ),
            'ListarTarefas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarTarefas,
                    request_deserializer=tarefas__pb2.ListaRequest.FromString,
                    response_serializer=tarefas__pb2.ListaResponse.SerializeToString,
            ),
            'AtualizarTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarTarefa,
                    request_deserializer=tarefas__pb2.TarefaAtualizacaoRequest.FromString,
                    response_serializer=tarefas__pb2.TarefaResponse.SerializeToString,
            ),
            'DeletarTarefa': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletarTarefa,
                    request_deserializer=tarefas__pb2.DeletarRequest.FromString,
                    response_serializer=tarefas__pb2.DeletarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tarefas.GerenciadorDeTarefas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tarefas.GerenciadorDeTarefas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GerenciadorDeTarefas:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.GerenciadorDeTarefas/CriarTarefa',
            tarefas__pb2.TarefaRequest.SerializeToString,
            tarefas__pb2.TarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarTarefas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.GerenciadorDeTarefas/ListarTarefas',
            tarefas__pb2.ListaRequest.SerializeToString,
            tarefas__pb2.ListaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.GerenciadorDeTarefas/AtualizarTarefa',
            tarefas__pb2.TarefaAtualizacaoRequest.SerializeToString,
            tarefas__pb2.TarefaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletarTarefa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarefas.GerenciadorDeTarefas/DeletarTarefa',
            tarefas__pb2.DeletarRequest.SerializeToString,
            tarefas__pb2.DeletarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
