# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefas.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tarefas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtarefas.proto\x12\x07tarefas\"q\n\x06Tarefa\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x61ta_limite\x18\x05 \x01(\t\x12\x13\n\x0bresponsavel\x18\x06 \x01(\t\"\\\n\rTarefaRequest\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x61ta_limite\x18\x03 \x01(\t\x12\x13\n\x0bresponsavel\x18\x04 \x01(\t\"C\n\x0eTarefaResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x1f\n\x06tarefa\x18\x02 \x01(\x0b\x32\x0f.tarefas.Tarefa\"\x0e\n\x0cListaRequest\"1\n\rListaResponse\x12 \n\x07tarefas\x18\x01 \x03(\x0b\x32\x0f.tarefas.Tarefa\"\x83\x01\n\x18TarefaAtualizacaoRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x61ta_limite\x18\x05 \x01(\t\x12\x13\n\x0bresponsavel\x18\x06 \x01(\t\"\x1c\n\x0e\x44\x65letarRequest\x12\n\n\x02id\x18\x01 \x01(\t\"4\n\x0f\x44\x65letarResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\x32\xa9\x02\n\x14GerenciadorDeTarefas\x12>\n\x0b\x43riarTarefa\x12\x16.tarefas.TarefaRequest\x1a\x17.tarefas.TarefaResponse\x12>\n\rListarTarefas\x12\x15.tarefas.ListaRequest\x1a\x16.tarefas.ListaResponse\x12M\n\x0f\x41tualizarTarefa\x12!.tarefas.TarefaAtualizacaoRequest\x1a\x17.tarefas.TarefaResponse\x12\x42\n\rDeletarTarefa\x12\x17.tarefas.DeletarRequest\x1a\x18.tarefas.DeletarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAREFA']._serialized_start=26
  _globals['_TAREFA']._serialized_end=139
  _globals['_TAREFAREQUEST']._serialized_start=141
  _globals['_TAREFAREQUEST']._serialized_end=233
  _globals['_TAREFARESPONSE']._serialized_start=235
  _globals['_TAREFARESPONSE']._serialized_end=302
  _globals['_LISTAREQUEST']._serialized_start=304
  _globals['_LISTAREQUEST']._serialized_end=318
  _globals['_LISTARESPONSE']._serialized_start=320
  _globals['_LISTARESPONSE']._serialized_end=369
  _globals['_TAREFAATUALIZACAOREQUEST']._serialized_start=372
  _globals['_TAREFAATUALIZACAOREQUEST']._serialized_end=503
  _globals['_DELETARREQUEST']._serialized_start=505
  _globals['_DELETARREQUEST']._serialized_end=533
  _globals['_DELETARRESPONSE']._serialized_start=535
  _globals['_DELETARRESPONSE']._serialized_end=587
  _globals['_GERENCIADORDETAREFAS']._serialized_start=590
  _globals['_GERENCIADORDETAREFAS']._serialized_end=887
# @@protoc_insertion_point(module_scope)
